### ISSUE TITLE
单聊发送文件的bug

### ISSUE THREAD

**Issue by 491134648** [jpush/jchat-web#1]
1.当单聊发送文件时，会出现发送中的bug，原因在于chat.reducer.ts中payload.msgs.content存在空引用时抛出了相关异常，修复方法为增加相关的非空判断
`// 发送消息完成（包括所有类型的消息）
        case chatAction.sendMsgComplete:
            sendMsgComplete(state, payload);
            if (payload.msgs) {
                const bussinessExtras = payload.msgs.content?(payload.msgs.content.msg_body?payload.msgs.content.msg_body.extras:null):null;
                if (bussinessExtras && bussinessExtras.businessCard && payload.success !== 2) {
                    state.sendBusinessCardSuccess = 0;
                } else {
                    state.sendBusinessCardSuccess++;
                }
            }
            break; `
以及这段代码

` 
for (let j = msgs.length - 1; j >= 0; j--) {
                if (msgs[j].msgKey && Number(payload.msgKey) === Number(msgs[j].msgKey)) {
                    if (payload.msgs && payload.success === 2) {
                        let url = msgs[j].content.msg_body.media_url;
                        let localExtras = msgs[j].content.msg_body.extras;
                        if (url) {
                            payload.msgs.content.msg_body.media_url = url;
                        }
                        if (localExtras && localExtras.businessCard) {
                            payload.msgs.content.msg_body.extras.media_url = localExtras.media_url;
                            payload.msgs.content.msg_body.extras.nickName = localExtras.nickName;
                        }
                        delete msgs[j].msg_id;
                        let from_name = payload.msgs.content?payload.msgs.content.from_name:null;
                        let nickname = msgs[j].content?msgs[j].content.from_name:null;
                        msgs[j] = Object.assign({}, msgs[j], payload.msgs);
                        if (!from_name) {
                            msgs[j].content.from_name = nickname;
                        }
                    }
                    msgs[j].success = payload.success;
                    console.log(msgs[j]);
                    return;
                }  
`

**Comment by xuwenqing2014** [comment]
问题已修复，在社区里回复你了
