### ISSUE TITLE
请问 error: must init first 怎么解决呢？

### ISSUE THREAD

**Issue by Zydiii** [jpush/jchat-web#10]
![image](https://user-images.githubusercontent.com/37077660/62094244-01291000-b2af-11e9-8b6c-20fe0ae0f8ec.png)
下载的原项目代码没有自己做过更改，将key改成自己注册的key之后，按照步骤npm run dev之后第一次运行很正常。
第二次npm run dev之后运行时点击登录按钮就报了must init first的错误。
请问是什么原因呢？需要做什么初始化吗？

**Comment by cidingtech** [comment]
同求这个问题！！！！！！

**Comment by xuwenqing2014** [comment]
key和masterSecret需要一起修改
