### ISSUE TITLE
不能显示移动端发送的视频消息。

### ISSUE THREAD

**Issue by caizetong** [jpush/jchat-web#12]
移动端发送到web端的视频无法显示。
web端发送一段视频，但其实发送的是文件，似乎没有相应的API可以发送视频，发送文件也没有相应的方法告诉SDK这是一个视频文件。所以移动端只能按文件处理。

**Comment by xuwenqing2014** [comment]
可以在msg_body.extras里面添加标识字段，标识视频文件做特殊处理
