### ISSUE TITLE
微信小程序中使用 sdk 报错

### ISSUE THREAD

**Issue by jaredchao** [jpush/jchat-web#3]
小程序 框架 使用的 mpvue

代码
```
import JMessage from '../static/js/jmessage-wxapplet-sdk-1.4.0.min.js'
var JIM = new JMessage();
Vue.mixin({
  data() {
    return {
      jim: ''
    }
  },
  created() {
      this.jim = JIM;
  }
})
```

小程序端出现 
![image](https://user-images.githubusercontent.com/9922823/46729061-dd142800-ccb6-11e8-8981-37db3d1bd371.png)

求助

**Comment by xuwenqing2014** [comment]
https://docs.jiguang.cn/jmessage/client/im_sdk_wxapplet/   这里有引入sdk的方式，请用require去引入sdk

**Comment by jaredchao** [comment]
> https://docs.jiguang.cn/jmessage/client/im_sdk_wxapplet/ 这里有引入sdk的方式，请用require去引入sdk

这样引入还是会报一样的错误！
